### ISSUE TITLE
detect far placed objects and small objects ?

### ISSUE THREAD

**Issue by prabhu-vinayaka** [rafaelpadilla/darknet#11]
Hi.
I have trained for detection of helmets.
Most of the training images are around 1.5 meters from the camera.
Now during testing,the model detects helmets up to 1.5 meters. (cannot detect far placed objects)
Is there a way to change any parameters to allow yolo to detect helmets at around 10 or 15 meters?( or should i add training data set for  each varying distance as well ?)
Is this disadvantage of my training data set or disadvantage yolo implementation ?
What parameters must be changed to detect far placed objects accurately?

Thank you.

**Comment by rafaelpadilla** [comment]
Dear @VinayakaPrabhu,

The network is supposed to detect what it is trained for. If your sample images contain objects up to 1.5 m from the camera, this is what it will detect.

You should include smaller objects  in your training (10 or 15 meters distant from the camera). Then your results will be improved.

Regards,
Rafael
