### ISSUE TITLE
Train with large image size like 1600*1200 with yolo

### ISSUE THREAD

**Issue by Ibmaria** [rafaelpadilla/darknet#13]
Hello @rafaelpadilla 
 I've read some other closed issues but still I don't understand how training with large image size. For instance my original size is 1600*1200. should I resize my original image before training? or it will be resized  automatically.Thanks in advance

**Comment by rafaelpadilla** [comment]
No you don't need to resize yourimages. Yolo v2 resizes the input image to different resolutions before passing to the CNNs.

Please, refer to the original paper for more details: [Paper Yolo9000](https://arxiv.org/pdf/1612.08242.pdf)

Regards

**Comment by Ibmaria** [comment]
Thanks @rafaelpadilla
