### ISSUE TITLE
Cannot load image Error: testing multiple images

### ISSUE THREAD

**Issue by filmnamu** [rafaelpadilla/darknet#3]
Hello,
I'm trying to test a detector with my own dataset, consists of 1 class data.
It is very well work for single image(own) and example multiple images(yours). But as shown below a "cannot load image" error occurrence in my own multiple images.

./darknet testimages newdata/voc.data newdata/own.cfg newdata/own.weights -savetxt -saveimg
![image](https://user-images.githubusercontent.com/4544730/43059654-79cdbbb0-8e88-11e8-864a-51e2cf9bf090.png)

What do you think I did wrong?
Please help me. Thanks in advance.

**Comment by rafaelpadilla** [comment]
dear @filmnamu ,

Were you able to run this code in your own images?

If possible, could you put those images in a remote folder and send it to me so I can test with it?

Best regards.

**Comment by filmnamu** [comment]
Dear @rafaelpadilla ,
I found out that the test image path was incorrectly.
The problem has now been resolved.
Thank you for your interest. : )
