### ISSUE TITLE
Segmentation fault while processing multiple images

### ISSUE THREAD

**Issue by chandang78** [rafaelpadilla/darknet#4]
Hi,
I trained a model over custom dataset (using AlexeyAB code) and I tried to process a batch of images with this repo using this command -

`./darknet testimages newdata/obj.data newdata/yolov3-tiny-obj.cfg newdata/yolov3-tiny-obj_4000.weights -savetxt -saveimg`

But I get this error - 

> Arguments:
dataFile: newdata/obj.data
cfgFile: newdata/yolov3-tiny-obj.cfg
weightsFile: newdata/yolov3-tiny-obj_4000.weights
thresh: 0.250000
hier_thresh: 0.500000
filename: (null)
saveImArg: -saveimg
saveTxtArg: -savetxt
showimg: (null)
Segmentation fault (core dumped)

Please help, let me know if you need any more info.

Thanks!

**Comment by rafaelpadilla** [comment]
Dear @chandang78 ,

This repository was designed to work with Yolo V2. Are you using Yolo V3?

I need to check your files (obj.data, yolov3-tiny-obj.cfg, yolov3-tiny-obj_4000.weights). Could you post them in a google drive and share the link with me, please?

Regards

**Comment by chandang78** [comment]
Hi,
Thank you for your time. Yes, I am using YOLOv3.
I didn't have much time, so wrote a crude script in python to draw the
predicted bounding boxes from the result.txt file generated when a batch of
images are given as input in the original darknet repo.

Once again Thank You
Regards
Chandan

**Comment by rafaelpadilla** [comment]
Mr. Chandan,

Nice! Thus I will consider this "issue" as closed.
