### ISSUE TITLE
save only class number

### ISSUE THREAD

**Issue by Jin-S-Kim** [rafaelpadilla/darknet#5]
Hi thanks for useful program.
Your program save multiple images and result of detection.
Txt file includes id confidence relative_center_x relative_center_y relative_width relative height.
Can I save only id confidence ??

**Comment by rafaelpadilla** [comment]
Dear @Jin-S-Kim ,

Yes. Modify [this line](https://github.com/rafaelpadilla/darknet/blob/master/examples/newfeatures.c#L378) keeping only what you want, recompile it and have fun :)

Regards

**Comment by Jin-S-Kim** [comment]
thank you very much !! it works well
