### ISSUE TITLE
Use yolov3.weights

### ISSUE THREAD

**Issue by Jin-S-Kim** [rafaelpadilla/darknet#6]
Hello rafaelpadilla! I want to use yolov3.weights in your code!
I use cfg file yolov3.cfg, yolov3.weights in darknet directory in github.
And I edit coco.data like this
classes= 80
train  = /home/pjreddie/data/coco/trainvalno5k.txt
valid  = coco_testdev
#valid = data/coco_val_5k.list
names = data/obj.names
backup = /home/pjreddie/backup/
eval=coco
test = test/test.txt
results = test/results

I insert terminal in my directory  
'./darknet testimages data/coco.data cfg/yolov3.cfg yolov3.weights -savetxt -saveimg'
but result is like this.

![image](https://user-images.githubusercontent.com/31817047/45665132-61f1a300-bb4a-11e8-987e-091af17d117e.png)
Can't I use yolov3.weights?

**Comment by rafaelpadilla** [comment]
Dear @Jin-S-Kim ,

No. This repository was created for Yolo V2. 

We haven't  commited the project for YoloV3 yet. We intend to do it soon though.

Regards,
Rafael
