### ISSUE TITLE
Object detection using infrared camera.

### ISSUE THREAD

**Issue by prabhu-vinayaka** [rafaelpadilla/darknet#9]
Hi. i have an infrared camera and can create lot of custom training images and annotation files.

Will using infrared camera files be useful to detect objects or using jpg images be useful?

Thank you.

Can we implement infrared images to detect objects in yolo framework?

**Comment by rafaelpadilla** [comment]
Dear @VinayakaPrabhu ,

Extra information such as signals coming from infrared spectrum may help object detectors.

There are public available datasets such as [LSI Far Infrared Pedestrian Dataset](https://e-archivo.uc3m.es/handle/10016/17370) and [Thermal Infrared Dataset](https://projects.asl.ethz.ch/datasets/doku.php?id=ir:iricra2014) that contain NIR and FIR images. You could search for works that use not only those, but other datasets for object detection and get deeper on the subject.

I have never gone deep on YOLO being used with infrared images, but maybe [this](http://uu.diva-portal.org/smash/get/diva2:1228617/FULLTEXT01.pdf) and [this](https://iiw.kuleuven.be/onderzoek/eavise/viper/viper_kvb) work might enlighten you a little.

Regards,
Rafael
